In [ ]:
# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.

In [30]:
import numpy as np

def generateMatrix(element,column):
    return np.column_stack([element**(column-1-i) for i in range(column)])

print(generateMatrix(np.array([1, 2, 3, 4,5]),4))

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]


In [34]:
import numpy as np

def generateMatrix(element,column):
    return np.column_stack([element**(i) for i in range(column)])

print(generateMatrix(np.array([1, 2, 3, 4,5]),4))

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]
